### ISSUE TITLE
graphs and images in the presentation slides

### ISSUE THREAD

**Issue by MayarLotfy** [OmarShaker97/Group-Repository-Sprint0#4]
lack of visual aids in the presentation slides as images and graphs;
kindly insert more descriptive images in the presentation slides as steps to be followed and screenshots of GitHub uses.

Mayar Lotfy

**Comment by YouhannaAdel** [comment]
[first graph](https://www.google.com.eg/search?hl=en&biw=1517&bih=735&tbm=isch&sa=1&ei=jq2BWo_aC8-jkwXCj4LQDw&q=github+activity+graph&oq=github+acti&gs_l=psy-ab.3.0.0l3j0i24k1l7.27439.29676.0.30649.7.6.1.0.0.0.188.709.0j5.5.0....0...1c.1.64.psy-ab..1.6.712...0i67k1j0i8i30k1.0.fx7mESgsQhU#imgrc=fC8lSycJ1J2r8M:)
[image](https://www.google.com.eg/search?hl=en&biw=1517&bih=735&tbm=isch&sa=1&ei=ra2BWtL5NtGTkwWjoYiwCw&q=github+&oq=github+&gs_l=psy-ab.3..0i67k1j0l2j0i67k1l2j0l2j0i67k1j0j0i67k1.79531.79531.0.79767.1.1.0.0.0.0.156.156.0j1.1.0....0...1c.1.64.psy-ab..0.1.154....0.3SkGB7b3EWw#imgrc=nE8c_QtK_Et2sM:)
